// Code generated by go-swagger; DO NOT EDIT.

package custom_rules

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/fugue/fugue-client/models"
)

// ValidateCustomRuleReader is a Reader for the ValidateCustomRule structure.
type ValidateCustomRuleReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ValidateCustomRuleReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 201:
		result := NewValidateCustomRuleCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 401:
		result := NewValidateCustomRuleUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 403:
		result := NewValidateCustomRuleForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 500:
		result := NewValidateCustomRuleInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewValidateCustomRuleCreated creates a ValidateCustomRuleCreated with default headers values
func NewValidateCustomRuleCreated() *ValidateCustomRuleCreated {
	return &ValidateCustomRuleCreated{}
}

/*ValidateCustomRuleCreated handles this case with default header values.

Validation results for the custom rule.
*/
type ValidateCustomRuleCreated struct {
	Payload *models.ValidateCustomRuleOutput
}

func (o *ValidateCustomRuleCreated) Error() string {
	return fmt.Sprintf("[POST /rules/validator/v1/{environment_id}][%d] validateCustomRuleCreated  %+v", 201, o.Payload)
}

func (o *ValidateCustomRuleCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ValidateCustomRuleOutput)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewValidateCustomRuleUnauthorized creates a ValidateCustomRuleUnauthorized with default headers values
func NewValidateCustomRuleUnauthorized() *ValidateCustomRuleUnauthorized {
	return &ValidateCustomRuleUnauthorized{}
}

/*ValidateCustomRuleUnauthorized handles this case with default header values.

AuthenticationError
*/
type ValidateCustomRuleUnauthorized struct {
	Payload *models.AuthenticationError
}

func (o *ValidateCustomRuleUnauthorized) Error() string {
	return fmt.Sprintf("[POST /rules/validator/v1/{environment_id}][%d] validateCustomRuleUnauthorized  %+v", 401, o.Payload)
}

func (o *ValidateCustomRuleUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.AuthenticationError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewValidateCustomRuleForbidden creates a ValidateCustomRuleForbidden with default headers values
func NewValidateCustomRuleForbidden() *ValidateCustomRuleForbidden {
	return &ValidateCustomRuleForbidden{}
}

/*ValidateCustomRuleForbidden handles this case with default header values.

AuthorizationError
*/
type ValidateCustomRuleForbidden struct {
	Payload *models.AuthorizationError
}

func (o *ValidateCustomRuleForbidden) Error() string {
	return fmt.Sprintf("[POST /rules/validator/v1/{environment_id}][%d] validateCustomRuleForbidden  %+v", 403, o.Payload)
}

func (o *ValidateCustomRuleForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.AuthorizationError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewValidateCustomRuleInternalServerError creates a ValidateCustomRuleInternalServerError with default headers values
func NewValidateCustomRuleInternalServerError() *ValidateCustomRuleInternalServerError {
	return &ValidateCustomRuleInternalServerError{}
}

/*ValidateCustomRuleInternalServerError handles this case with default header values.

InternalServerError
*/
type ValidateCustomRuleInternalServerError struct {
	Payload *models.InternalServerError
}

func (o *ValidateCustomRuleInternalServerError) Error() string {
	return fmt.Sprintf("[POST /rules/validator/v1/{environment_id}][%d] validateCustomRuleInternalServerError  %+v", 500, o.Payload)
}

func (o *ValidateCustomRuleInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.InternalServerError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
