// Code generated by go-swagger; DO NOT EDIT.

package invites

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/fugue/fugue-client/models"
)

// GetInviteByEmailReader is a Reader for the GetInviteByEmail structure.
type GetInviteByEmailReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetInviteByEmailReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetInviteByEmailOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetInviteByEmailBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewGetInviteByEmailUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewGetInviteByEmailForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetInviteByEmailNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetInviteByEmailInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetInviteByEmailOK creates a GetInviteByEmailOK with default headers values
func NewGetInviteByEmailOK() *GetInviteByEmailOK {
	return &GetInviteByEmailOK{}
}

/*GetInviteByEmailOK handles this case with default header values.

Invite details.
*/
type GetInviteByEmailOK struct {
	Payload *models.Invite
}

func (o *GetInviteByEmailOK) Error() string {
	return fmt.Sprintf("[GET /invites/][%d] getInviteByEmailOK  %+v", 200, o.Payload)
}

func (o *GetInviteByEmailOK) GetPayload() *models.Invite {
	return o.Payload
}

func (o *GetInviteByEmailOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Invite)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetInviteByEmailBadRequest creates a GetInviteByEmailBadRequest with default headers values
func NewGetInviteByEmailBadRequest() *GetInviteByEmailBadRequest {
	return &GetInviteByEmailBadRequest{}
}

/*GetInviteByEmailBadRequest handles this case with default header values.

Bad request error.
*/
type GetInviteByEmailBadRequest struct {
	Payload *models.BadRequestError
}

func (o *GetInviteByEmailBadRequest) Error() string {
	return fmt.Sprintf("[GET /invites/][%d] getInviteByEmailBadRequest  %+v", 400, o.Payload)
}

func (o *GetInviteByEmailBadRequest) GetPayload() *models.BadRequestError {
	return o.Payload
}

func (o *GetInviteByEmailBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.BadRequestError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetInviteByEmailUnauthorized creates a GetInviteByEmailUnauthorized with default headers values
func NewGetInviteByEmailUnauthorized() *GetInviteByEmailUnauthorized {
	return &GetInviteByEmailUnauthorized{}
}

/*GetInviteByEmailUnauthorized handles this case with default header values.

Authentication error.
*/
type GetInviteByEmailUnauthorized struct {
	Payload *models.AuthenticationError
}

func (o *GetInviteByEmailUnauthorized) Error() string {
	return fmt.Sprintf("[GET /invites/][%d] getInviteByEmailUnauthorized  %+v", 401, o.Payload)
}

func (o *GetInviteByEmailUnauthorized) GetPayload() *models.AuthenticationError {
	return o.Payload
}

func (o *GetInviteByEmailUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.AuthenticationError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetInviteByEmailForbidden creates a GetInviteByEmailForbidden with default headers values
func NewGetInviteByEmailForbidden() *GetInviteByEmailForbidden {
	return &GetInviteByEmailForbidden{}
}

/*GetInviteByEmailForbidden handles this case with default header values.

Authorization error.
*/
type GetInviteByEmailForbidden struct {
	Payload *models.AuthorizationError
}

func (o *GetInviteByEmailForbidden) Error() string {
	return fmt.Sprintf("[GET /invites/][%d] getInviteByEmailForbidden  %+v", 403, o.Payload)
}

func (o *GetInviteByEmailForbidden) GetPayload() *models.AuthorizationError {
	return o.Payload
}

func (o *GetInviteByEmailForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.AuthorizationError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetInviteByEmailNotFound creates a GetInviteByEmailNotFound with default headers values
func NewGetInviteByEmailNotFound() *GetInviteByEmailNotFound {
	return &GetInviteByEmailNotFound{}
}

/*GetInviteByEmailNotFound handles this case with default header values.

Not found error.
*/
type GetInviteByEmailNotFound struct {
	Payload *models.NotFoundError
}

func (o *GetInviteByEmailNotFound) Error() string {
	return fmt.Sprintf("[GET /invites/][%d] getInviteByEmailNotFound  %+v", 404, o.Payload)
}

func (o *GetInviteByEmailNotFound) GetPayload() *models.NotFoundError {
	return o.Payload
}

func (o *GetInviteByEmailNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.NotFoundError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetInviteByEmailInternalServerError creates a GetInviteByEmailInternalServerError with default headers values
func NewGetInviteByEmailInternalServerError() *GetInviteByEmailInternalServerError {
	return &GetInviteByEmailInternalServerError{}
}

/*GetInviteByEmailInternalServerError handles this case with default header values.

Internal server error.
*/
type GetInviteByEmailInternalServerError struct {
	Payload *models.InternalServerError
}

func (o *GetInviteByEmailInternalServerError) Error() string {
	return fmt.Sprintf("[GET /invites/][%d] getInviteByEmailInternalServerError  %+v", 500, o.Payload)
}

func (o *GetInviteByEmailInternalServerError) GetPayload() *models.InternalServerError {
	return o.Payload
}

func (o *GetInviteByEmailInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.InternalServerError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
