// Code generated by go-swagger; DO NOT EDIT.

package users

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/fugue/fugue-client/models"
)

// GetUserByEmailReader is a Reader for the GetUserByEmail structure.
type GetUserByEmailReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetUserByEmailReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetUserByEmailOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetUserByEmailBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewGetUserByEmailUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewGetUserByEmailForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetUserByEmailNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetUserByEmailInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetUserByEmailOK creates a GetUserByEmailOK with default headers values
func NewGetUserByEmailOK() *GetUserByEmailOK {
	return &GetUserByEmailOK{}
}

/*GetUserByEmailOK handles this case with default header values.

User details.
*/
type GetUserByEmailOK struct {
	Payload *models.User
}

func (o *GetUserByEmailOK) Error() string {
	return fmt.Sprintf("[GET /users/][%d] getUserByEmailOK  %+v", 200, o.Payload)
}

func (o *GetUserByEmailOK) GetPayload() *models.User {
	return o.Payload
}

func (o *GetUserByEmailOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.User)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetUserByEmailBadRequest creates a GetUserByEmailBadRequest with default headers values
func NewGetUserByEmailBadRequest() *GetUserByEmailBadRequest {
	return &GetUserByEmailBadRequest{}
}

/*GetUserByEmailBadRequest handles this case with default header values.

Bad request error.
*/
type GetUserByEmailBadRequest struct {
	Payload *models.BadRequestError
}

func (o *GetUserByEmailBadRequest) Error() string {
	return fmt.Sprintf("[GET /users/][%d] getUserByEmailBadRequest  %+v", 400, o.Payload)
}

func (o *GetUserByEmailBadRequest) GetPayload() *models.BadRequestError {
	return o.Payload
}

func (o *GetUserByEmailBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.BadRequestError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetUserByEmailUnauthorized creates a GetUserByEmailUnauthorized with default headers values
func NewGetUserByEmailUnauthorized() *GetUserByEmailUnauthorized {
	return &GetUserByEmailUnauthorized{}
}

/*GetUserByEmailUnauthorized handles this case with default header values.

Authentication error.
*/
type GetUserByEmailUnauthorized struct {
	Payload *models.AuthenticationError
}

func (o *GetUserByEmailUnauthorized) Error() string {
	return fmt.Sprintf("[GET /users/][%d] getUserByEmailUnauthorized  %+v", 401, o.Payload)
}

func (o *GetUserByEmailUnauthorized) GetPayload() *models.AuthenticationError {
	return o.Payload
}

func (o *GetUserByEmailUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.AuthenticationError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetUserByEmailForbidden creates a GetUserByEmailForbidden with default headers values
func NewGetUserByEmailForbidden() *GetUserByEmailForbidden {
	return &GetUserByEmailForbidden{}
}

/*GetUserByEmailForbidden handles this case with default header values.

Authorization error.
*/
type GetUserByEmailForbidden struct {
	Payload *models.AuthorizationError
}

func (o *GetUserByEmailForbidden) Error() string {
	return fmt.Sprintf("[GET /users/][%d] getUserByEmailForbidden  %+v", 403, o.Payload)
}

func (o *GetUserByEmailForbidden) GetPayload() *models.AuthorizationError {
	return o.Payload
}

func (o *GetUserByEmailForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.AuthorizationError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetUserByEmailNotFound creates a GetUserByEmailNotFound with default headers values
func NewGetUserByEmailNotFound() *GetUserByEmailNotFound {
	return &GetUserByEmailNotFound{}
}

/*GetUserByEmailNotFound handles this case with default header values.

Not found error.
*/
type GetUserByEmailNotFound struct {
	Payload *models.NotFoundError
}

func (o *GetUserByEmailNotFound) Error() string {
	return fmt.Sprintf("[GET /users/][%d] getUserByEmailNotFound  %+v", 404, o.Payload)
}

func (o *GetUserByEmailNotFound) GetPayload() *models.NotFoundError {
	return o.Payload
}

func (o *GetUserByEmailNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.NotFoundError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetUserByEmailInternalServerError creates a GetUserByEmailInternalServerError with default headers values
func NewGetUserByEmailInternalServerError() *GetUserByEmailInternalServerError {
	return &GetUserByEmailInternalServerError{}
}

/*GetUserByEmailInternalServerError handles this case with default header values.

Internal server error.
*/
type GetUserByEmailInternalServerError struct {
	Payload *models.InternalServerError
}

func (o *GetUserByEmailInternalServerError) Error() string {
	return fmt.Sprintf("[GET /users/][%d] getUserByEmailInternalServerError  %+v", 500, o.Payload)
}

func (o *GetUserByEmailInternalServerError) GetPayload() *models.InternalServerError {
	return o.Payload
}

func (o *GetUserByEmailInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.InternalServerError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
