// Code generated by go-swagger; DO NOT EDIT.

package c_o_r_s

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// New creates a new c o r s API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) *Client {
	return &Client{transport: transport, formats: formats}
}

/*
Client for c o r s API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

/*
OptionsRules cs o r s support

Enable CORS by returning correct headers.

*/
func (a *Client) OptionsRules(params *OptionsRulesParams) (*OptionsRulesOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewOptionsRulesParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "OptionsRules",
		Method:             "OPTIONS",
		PathPattern:        "/rules",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &OptionsRulesReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*OptionsRulesOK), nil

}

/*
OptionsRulesRuleID cs o r s support

Enable CORS by returning correct headers.

*/
func (a *Client) OptionsRulesRuleID(params *OptionsRulesRuleIDParams) (*OptionsRulesRuleIDOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewOptionsRulesRuleIDParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "OptionsRulesRuleID",
		Method:             "OPTIONS",
		PathPattern:        "/rules/{rule_id}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &OptionsRulesRuleIDReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*OptionsRulesRuleIDOK), nil

}

/*
OptionsRulesValidatorV1EnvironmentID cs o r s support

Enable CORS by returning correct headers.

*/
func (a *Client) OptionsRulesValidatorV1EnvironmentID(params *OptionsRulesValidatorV1EnvironmentIDParams) (*OptionsRulesValidatorV1EnvironmentIDOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewOptionsRulesValidatorV1EnvironmentIDParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "OptionsRulesValidatorV1EnvironmentID",
		Method:             "OPTIONS",
		PathPattern:        "/rules/validator/v1/{environment_id}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &OptionsRulesValidatorV1EnvironmentIDReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*OptionsRulesValidatorV1EnvironmentIDOK), nil

}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
