// Code generated by go-swagger; DO NOT EDIT.

package c_o_r_s

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewOptionsRulesValidatorV1EnvironmentIDParams creates a new OptionsRulesValidatorV1EnvironmentIDParams object
// with the default values initialized.
func NewOptionsRulesValidatorV1EnvironmentIDParams() *OptionsRulesValidatorV1EnvironmentIDParams {
	var ()
	return &OptionsRulesValidatorV1EnvironmentIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewOptionsRulesValidatorV1EnvironmentIDParamsWithTimeout creates a new OptionsRulesValidatorV1EnvironmentIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewOptionsRulesValidatorV1EnvironmentIDParamsWithTimeout(timeout time.Duration) *OptionsRulesValidatorV1EnvironmentIDParams {
	var ()
	return &OptionsRulesValidatorV1EnvironmentIDParams{

		timeout: timeout,
	}
}

// NewOptionsRulesValidatorV1EnvironmentIDParamsWithContext creates a new OptionsRulesValidatorV1EnvironmentIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewOptionsRulesValidatorV1EnvironmentIDParamsWithContext(ctx context.Context) *OptionsRulesValidatorV1EnvironmentIDParams {
	var ()
	return &OptionsRulesValidatorV1EnvironmentIDParams{

		Context: ctx,
	}
}

// NewOptionsRulesValidatorV1EnvironmentIDParamsWithHTTPClient creates a new OptionsRulesValidatorV1EnvironmentIDParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewOptionsRulesValidatorV1EnvironmentIDParamsWithHTTPClient(client *http.Client) *OptionsRulesValidatorV1EnvironmentIDParams {
	var ()
	return &OptionsRulesValidatorV1EnvironmentIDParams{
		HTTPClient: client,
	}
}

/*OptionsRulesValidatorV1EnvironmentIDParams contains all the parameters to send to the API endpoint
for the options rules validator v1 environment ID operation typically these are written to a http.Request
*/
type OptionsRulesValidatorV1EnvironmentIDParams struct {

	/*EnvironmentID
	  The id of the environment against which to validate the rule.

	*/
	EnvironmentID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the options rules validator v1 environment ID params
func (o *OptionsRulesValidatorV1EnvironmentIDParams) WithTimeout(timeout time.Duration) *OptionsRulesValidatorV1EnvironmentIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the options rules validator v1 environment ID params
func (o *OptionsRulesValidatorV1EnvironmentIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the options rules validator v1 environment ID params
func (o *OptionsRulesValidatorV1EnvironmentIDParams) WithContext(ctx context.Context) *OptionsRulesValidatorV1EnvironmentIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the options rules validator v1 environment ID params
func (o *OptionsRulesValidatorV1EnvironmentIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the options rules validator v1 environment ID params
func (o *OptionsRulesValidatorV1EnvironmentIDParams) WithHTTPClient(client *http.Client) *OptionsRulesValidatorV1EnvironmentIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the options rules validator v1 environment ID params
func (o *OptionsRulesValidatorV1EnvironmentIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithEnvironmentID adds the environmentID to the options rules validator v1 environment ID params
func (o *OptionsRulesValidatorV1EnvironmentIDParams) WithEnvironmentID(environmentID string) *OptionsRulesValidatorV1EnvironmentIDParams {
	o.SetEnvironmentID(environmentID)
	return o
}

// SetEnvironmentID adds the environmentId to the options rules validator v1 environment ID params
func (o *OptionsRulesValidatorV1EnvironmentIDParams) SetEnvironmentID(environmentID string) {
	o.EnvironmentID = environmentID
}

// WriteToRequest writes these params to a swagger request
func (o *OptionsRulesValidatorV1EnvironmentIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param environment_id
	if err := r.SetPathParam("environment_id", o.EnvironmentID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
