// Code generated by go-swagger; DO NOT EDIT.

package c_o_r_s

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewOptionsRulesTestParams creates a new OptionsRulesTestParams object
// with the default values initialized.
func NewOptionsRulesTestParams() *OptionsRulesTestParams {

	return &OptionsRulesTestParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewOptionsRulesTestParamsWithTimeout creates a new OptionsRulesTestParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewOptionsRulesTestParamsWithTimeout(timeout time.Duration) *OptionsRulesTestParams {

	return &OptionsRulesTestParams{

		timeout: timeout,
	}
}

// NewOptionsRulesTestParamsWithContext creates a new OptionsRulesTestParams object
// with the default values initialized, and the ability to set a context for a request
func NewOptionsRulesTestParamsWithContext(ctx context.Context) *OptionsRulesTestParams {

	return &OptionsRulesTestParams{

		Context: ctx,
	}
}

// NewOptionsRulesTestParamsWithHTTPClient creates a new OptionsRulesTestParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewOptionsRulesTestParamsWithHTTPClient(client *http.Client) *OptionsRulesTestParams {

	return &OptionsRulesTestParams{
		HTTPClient: client,
	}
}

/*OptionsRulesTestParams contains all the parameters to send to the API endpoint
for the options rules test operation typically these are written to a http.Request
*/
type OptionsRulesTestParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the options rules test params
func (o *OptionsRulesTestParams) WithTimeout(timeout time.Duration) *OptionsRulesTestParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the options rules test params
func (o *OptionsRulesTestParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the options rules test params
func (o *OptionsRulesTestParams) WithContext(ctx context.Context) *OptionsRulesTestParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the options rules test params
func (o *OptionsRulesTestParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the options rules test params
func (o *OptionsRulesTestParams) WithHTTPClient(client *http.Client) *OptionsRulesTestParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the options rules test params
func (o *OptionsRulesTestParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *OptionsRulesTestParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
