// Code generated by go-swagger; DO NOT EDIT.

package c_o_r_s

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// OptionsRulesValidatorV1EnvironmentIDReader is a Reader for the OptionsRulesValidatorV1EnvironmentID structure.
type OptionsRulesValidatorV1EnvironmentIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *OptionsRulesValidatorV1EnvironmentIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewOptionsRulesValidatorV1EnvironmentIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewOptionsRulesValidatorV1EnvironmentIDOK creates a OptionsRulesValidatorV1EnvironmentIDOK with default headers values
func NewOptionsRulesValidatorV1EnvironmentIDOK() *OptionsRulesValidatorV1EnvironmentIDOK {
	return &OptionsRulesValidatorV1EnvironmentIDOK{}
}

/*OptionsRulesValidatorV1EnvironmentIDOK handles this case with default header values.

Default response for CORS method
*/
type OptionsRulesValidatorV1EnvironmentIDOK struct {
	AccessControlAllowHeaders string

	AccessControlAllowMethods string

	AccessControlAllowOrigin string
}

func (o *OptionsRulesValidatorV1EnvironmentIDOK) Error() string {
	return fmt.Sprintf("[OPTIONS /rules/validator/v1/{environment_id}][%d] optionsRulesValidatorV1EnvironmentIdOK ", 200)
}

func (o *OptionsRulesValidatorV1EnvironmentIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response header Access-Control-Allow-Headers
	o.AccessControlAllowHeaders = response.GetHeader("Access-Control-Allow-Headers")

	// response header Access-Control-Allow-Methods
	o.AccessControlAllowMethods = response.GetHeader("Access-Control-Allow-Methods")

	// response header Access-Control-Allow-Origin
	o.AccessControlAllowOrigin = response.GetHeader("Access-Control-Allow-Origin")

	return nil
}
