// Code generated by go-swagger; DO NOT EDIT.

package c_o_r_s

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewOptionsRulesTestInputParams creates a new OptionsRulesTestInputParams object
// with the default values initialized.
func NewOptionsRulesTestInputParams() *OptionsRulesTestInputParams {

	return &OptionsRulesTestInputParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewOptionsRulesTestInputParamsWithTimeout creates a new OptionsRulesTestInputParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewOptionsRulesTestInputParamsWithTimeout(timeout time.Duration) *OptionsRulesTestInputParams {

	return &OptionsRulesTestInputParams{

		timeout: timeout,
	}
}

// NewOptionsRulesTestInputParamsWithContext creates a new OptionsRulesTestInputParams object
// with the default values initialized, and the ability to set a context for a request
func NewOptionsRulesTestInputParamsWithContext(ctx context.Context) *OptionsRulesTestInputParams {

	return &OptionsRulesTestInputParams{

		Context: ctx,
	}
}

// NewOptionsRulesTestInputParamsWithHTTPClient creates a new OptionsRulesTestInputParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewOptionsRulesTestInputParamsWithHTTPClient(client *http.Client) *OptionsRulesTestInputParams {

	return &OptionsRulesTestInputParams{
		HTTPClient: client,
	}
}

/*OptionsRulesTestInputParams contains all the parameters to send to the API endpoint
for the options rules test input operation typically these are written to a http.Request
*/
type OptionsRulesTestInputParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the options rules test input params
func (o *OptionsRulesTestInputParams) WithTimeout(timeout time.Duration) *OptionsRulesTestInputParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the options rules test input params
func (o *OptionsRulesTestInputParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the options rules test input params
func (o *OptionsRulesTestInputParams) WithContext(ctx context.Context) *OptionsRulesTestInputParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the options rules test input params
func (o *OptionsRulesTestInputParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the options rules test input params
func (o *OptionsRulesTestInputParams) WithHTTPClient(client *http.Client) *OptionsRulesTestInputParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the options rules test input params
func (o *OptionsRulesTestInputParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *OptionsRulesTestInputParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
