// Code generated by go-swagger; DO NOT EDIT.

package c_o_r_s

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewOptionsRulesParams creates a new OptionsRulesParams object
// with the default values initialized.
func NewOptionsRulesParams() *OptionsRulesParams {

	return &OptionsRulesParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewOptionsRulesParamsWithTimeout creates a new OptionsRulesParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewOptionsRulesParamsWithTimeout(timeout time.Duration) *OptionsRulesParams {

	return &OptionsRulesParams{

		timeout: timeout,
	}
}

// NewOptionsRulesParamsWithContext creates a new OptionsRulesParams object
// with the default values initialized, and the ability to set a context for a request
func NewOptionsRulesParamsWithContext(ctx context.Context) *OptionsRulesParams {

	return &OptionsRulesParams{

		Context: ctx,
	}
}

// NewOptionsRulesParamsWithHTTPClient creates a new OptionsRulesParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewOptionsRulesParamsWithHTTPClient(client *http.Client) *OptionsRulesParams {

	return &OptionsRulesParams{
		HTTPClient: client,
	}
}

/*OptionsRulesParams contains all the parameters to send to the API endpoint
for the options rules operation typically these are written to a http.Request
*/
type OptionsRulesParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the options rules params
func (o *OptionsRulesParams) WithTimeout(timeout time.Duration) *OptionsRulesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the options rules params
func (o *OptionsRulesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the options rules params
func (o *OptionsRulesParams) WithContext(ctx context.Context) *OptionsRulesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the options rules params
func (o *OptionsRulesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the options rules params
func (o *OptionsRulesParams) WithHTTPClient(client *http.Client) *OptionsRulesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the options rules params
func (o *OptionsRulesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *OptionsRulesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
