// Code generated by go-swagger; DO NOT EDIT.

package metadata

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/fugue/fugue-client/models"
)

// GetResourceTypesReader is a Reader for the GetResourceTypes structure.
type GetResourceTypesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetResourceTypesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetResourceTypesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 500:
		result := NewGetResourceTypesInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetResourceTypesOK creates a GetResourceTypesOK with default headers values
func NewGetResourceTypesOK() *GetResourceTypesOK {
	return &GetResourceTypesOK{}
}

/*GetResourceTypesOK handles this case with default header values.

List of supported resource types.
*/
type GetResourceTypesOK struct {
	Payload *models.ResourceTypeMetadata
}

func (o *GetResourceTypesOK) Error() string {
	return fmt.Sprintf("[GET /metadata/{provider}/resource_types][%d] getResourceTypesOK  %+v", 200, o.Payload)
}

func (o *GetResourceTypesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResourceTypeMetadata)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetResourceTypesInternalServerError creates a GetResourceTypesInternalServerError with default headers values
func NewGetResourceTypesInternalServerError() *GetResourceTypesInternalServerError {
	return &GetResourceTypesInternalServerError{}
}

/*GetResourceTypesInternalServerError handles this case with default header values.

Internal server error.
*/
type GetResourceTypesInternalServerError struct {
	Payload *models.InternalServerError
}

func (o *GetResourceTypesInternalServerError) Error() string {
	return fmt.Sprintf("[GET /metadata/{provider}/resource_types][%d] getResourceTypesInternalServerError  %+v", 500, o.Payload)
}

func (o *GetResourceTypesInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.InternalServerError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
