// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// ComplianceDiffRulesItems compliance diff rules items
// swagger:model complianceDiffRulesItems
type ComplianceDiffRulesItems struct {

	// The compliance families that a rule is evaluated for.
	ComplianceFamilies []string `json:"compliance_families"`

	// The compliance controls that a rule is evaluated for.
	Controls []string `json:"controls"`

	// The rule's error message after an event.
	NewMessage string `json:"new_message"`

	// The rule's evaluation state after an event.
	NewState string `json:"new_state"`

	// The rule's error message before an event.
	OldMessage string `json:"old_message"`

	// The rule's evaluation state before an event.
	OldState string `json:"old_state"`

	// Summary of the rule a resource was evaluated against.
	Summary string `json:"summary"`
}

// Validate validates this compliance diff rules items
func (m *ComplianceDiffRulesItems) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ComplianceDiffRulesItems) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ComplianceDiffRulesItems) UnmarshalBinary(b []byte) error {
	var res ComplianceDiffRulesItems
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
