// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// ComplianceByRuleFailedResourcesItems Resource that failed to satisfy the rule due to a misconfiguration in the resource and associated error messages.
// swagger:model complianceByRuleFailedResourcesItems
type ComplianceByRuleFailedResourcesItems struct {

	// Messages why the rule failed.
	Messages []string `json:"messages"`

	// resource
	Resource *Resource `json:"resource"`
}

// Validate validates this compliance by rule failed resources items
func (m *ComplianceByRuleFailedResourcesItems) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateResource(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ComplianceByRuleFailedResourcesItems) validateResource(formats strfmt.Registry) error {

	if swag.IsZero(m.Resource) { // not required
		return nil
	}

	if m.Resource != nil {
		if err := m.Resource.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("resource")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *ComplianceByRuleFailedResourcesItems) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ComplianceByRuleFailedResourcesItems) UnmarshalBinary(b []byte) error {
	var res ComplianceByRuleFailedResourcesItems
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
