// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// CreateCustomRuleInput Input request for creating a custom rule.
//
// swagger:model CreateCustomRuleInput
type CreateCustomRuleInput struct {

	// Description of the custom rule
	Description string `json:"description,omitempty"`

	// Human readable name of the custom rule
	Name string `json:"name,omitempty"`

	// Provider of the custom rule
	// Enum: [AWS AWS_GOVCLOUD AZURE]
	Provider string `json:"provider,omitempty"`

	// Resource type to which the custom rule applies
	ResourceType string `json:"resource_type,omitempty"`

	// The rego source code for the rule
	RuleText string `json:"rule_text,omitempty"`

	// The origin of this rule
	// Enum: [FUGUE CUSTOM]
	Source string `json:"source,omitempty"`
}

// Validate validates this create custom rule input
func (m *CreateCustomRuleInput) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateProvider(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateSource(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

var createCustomRuleInputTypeProviderPropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["AWS","AWS_GOVCLOUD","AZURE"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		createCustomRuleInputTypeProviderPropEnum = append(createCustomRuleInputTypeProviderPropEnum, v)
	}
}

const (

	// CreateCustomRuleInputProviderAWS captures enum value "AWS"
	CreateCustomRuleInputProviderAWS string = "AWS"

	// CreateCustomRuleInputProviderAWSGOVCLOUD captures enum value "AWS_GOVCLOUD"
	CreateCustomRuleInputProviderAWSGOVCLOUD string = "AWS_GOVCLOUD"

	// CreateCustomRuleInputProviderAZURE captures enum value "AZURE"
	CreateCustomRuleInputProviderAZURE string = "AZURE"
)

// prop value enum
func (m *CreateCustomRuleInput) validateProviderEnum(path, location string, value string) error {
	if err := validate.Enum(path, location, value, createCustomRuleInputTypeProviderPropEnum); err != nil {
		return err
	}
	return nil
}

func (m *CreateCustomRuleInput) validateProvider(formats strfmt.Registry) error {

	if swag.IsZero(m.Provider) { // not required
		return nil
	}

	// value enum
	if err := m.validateProviderEnum("provider", "body", m.Provider); err != nil {
		return err
	}

	return nil
}

var createCustomRuleInputTypeSourcePropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["FUGUE","CUSTOM"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		createCustomRuleInputTypeSourcePropEnum = append(createCustomRuleInputTypeSourcePropEnum, v)
	}
}

const (

	// CreateCustomRuleInputSourceFUGUE captures enum value "FUGUE"
	CreateCustomRuleInputSourceFUGUE string = "FUGUE"

	// CreateCustomRuleInputSourceCUSTOM captures enum value "CUSTOM"
	CreateCustomRuleInputSourceCUSTOM string = "CUSTOM"
)

// prop value enum
func (m *CreateCustomRuleInput) validateSourceEnum(path, location string, value string) error {
	if err := validate.Enum(path, location, value, createCustomRuleInputTypeSourcePropEnum); err != nil {
		return err
	}
	return nil
}

func (m *CreateCustomRuleInput) validateSource(formats strfmt.Registry) error {

	if swag.IsZero(m.Source) { // not required
		return nil
	}

	// value enum
	if err := m.validateSourceEnum("source", "body", m.Source); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *CreateCustomRuleInput) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CreateCustomRuleInput) UnmarshalBinary(b []byte) error {
	var res CreateCustomRuleInput
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
