// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// EnvironmentWithSummaryAllOf1 environment with summary all of1
// swagger:model environmentWithSummaryAllOf1
type EnvironmentWithSummaryAllOf1 struct {

	// resource summary
	ResourceSummary *ResourceSummary `json:"resource_summary"`
}

// Validate validates this environment with summary all of1
func (m *EnvironmentWithSummaryAllOf1) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateResourceSummary(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *EnvironmentWithSummaryAllOf1) validateResourceSummary(formats strfmt.Registry) error {

	if swag.IsZero(m.ResourceSummary) { // not required
		return nil
	}

	if m.ResourceSummary != nil {
		if err := m.ResourceSummary.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("resource_summary")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *EnvironmentWithSummaryAllOf1) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *EnvironmentWithSummaryAllOf1) UnmarshalBinary(b []byte) error {
	var res EnvironmentWithSummaryAllOf1
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
