// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// FamiliesFilterOutput Filters for families table
//
// swagger:model FamiliesFilterOutput
type FamiliesFilterOutput struct {

	// provider
	Provider *FamiliesFilterOutputProvider `json:"provider,omitempty"`

	// source
	Source *FamiliesFilterOutputSource `json:"source,omitempty"`
}

// Validate validates this families filter output
func (m *FamiliesFilterOutput) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateProvider(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateSource(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *FamiliesFilterOutput) validateProvider(formats strfmt.Registry) error {

	if swag.IsZero(m.Provider) { // not required
		return nil
	}

	if m.Provider != nil {
		if err := m.Provider.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("provider")
			}
			return err
		}
	}

	return nil
}

func (m *FamiliesFilterOutput) validateSource(formats strfmt.Registry) error {

	if swag.IsZero(m.Source) { // not required
		return nil
	}

	if m.Source != nil {
		if err := m.Source.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("source")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *FamiliesFilterOutput) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *FamiliesFilterOutput) UnmarshalBinary(b []byte) error {
	var res FamiliesFilterOutput
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}

// FamiliesFilterOutputProvider families filter output provider
//
// swagger:model FamiliesFilterOutputProvider
type FamiliesFilterOutputProvider struct {

	// aws
	Aws int64 `json:"aws,omitempty"`

	// azure
	Azure int64 `json:"azure,omitempty"`

	// google
	Google int64 `json:"google,omitempty"`

	// govcloud
	Govcloud int64 `json:"govcloud,omitempty"`
}

// Validate validates this families filter output provider
func (m *FamiliesFilterOutputProvider) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *FamiliesFilterOutputProvider) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *FamiliesFilterOutputProvider) UnmarshalBinary(b []byte) error {
	var res FamiliesFilterOutputProvider
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}

// FamiliesFilterOutputSource families filter output source
//
// swagger:model FamiliesFilterOutputSource
type FamiliesFilterOutputSource struct {

	// custom
	Custom int64 `json:"custom,omitempty"`

	// fugue
	Fugue int64 `json:"fugue,omitempty"`
}

// Validate validates this families filter output source
func (m *FamiliesFilterOutputSource) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *FamiliesFilterOutputSource) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *FamiliesFilterOutputSource) UnmarshalBinary(b []byte) error {
	var res FamiliesFilterOutputSource
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
