// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// NonCompliantResourceFailedRulesItems non compliant resource failed rules items
// swagger:model nonCompliantResourceFailedRulesItems
type NonCompliantResourceFailedRulesItems struct {

	// Compliance family the violated rule belongs to.
	Family string `json:"family"`

	// Reasons the resource was found in violation of a rule.
	Messages []string `json:"messages"`

	// ID of the violated rule.
	Rule string `json:"rule"`
}

// Validate validates this non compliant resource failed rules items
func (m *NonCompliantResourceFailedRulesItems) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *NonCompliantResourceFailedRulesItems) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *NonCompliantResourceFailedRulesItems) UnmarshalBinary(b []byte) error {
	var res NonCompliantResourceFailedRulesItems
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
