// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// RuleValidationError A single error from validating a rule
// swagger:model RuleValidationError
type RuleValidationError struct {

	// Error type
	ErrorType string `json:"error_type,omitempty"`

	// Error message
	Message string `json:"message,omitempty"`
}

// Validate validates this rule validation error
func (m *RuleValidationError) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *RuleValidationError) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *RuleValidationError) UnmarshalBinary(b []byte) error {
	var res RuleValidationError
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
