// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// ScanWithSummaryAllOf1 scan with summary all of1
// swagger:model scanWithSummaryAllOf1
type ScanWithSummaryAllOf1 struct {

	// resource summary
	ResourceSummary *ResourceSummary `json:"resource_summary"`

	// resource type errors
	ResourceTypeErrors []*ScanWithSummaryAllOf1ResourceTypeErrorsItems `json:"resource_type_errors"`
}

// Validate validates this scan with summary all of1
func (m *ScanWithSummaryAllOf1) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateResourceSummary(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateResourceTypeErrors(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ScanWithSummaryAllOf1) validateResourceSummary(formats strfmt.Registry) error {

	if swag.IsZero(m.ResourceSummary) { // not required
		return nil
	}

	if m.ResourceSummary != nil {
		if err := m.ResourceSummary.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("resource_summary")
			}
			return err
		}
	}

	return nil
}

func (m *ScanWithSummaryAllOf1) validateResourceTypeErrors(formats strfmt.Registry) error {

	if swag.IsZero(m.ResourceTypeErrors) { // not required
		return nil
	}

	for i := 0; i < len(m.ResourceTypeErrors); i++ {
		if swag.IsZero(m.ResourceTypeErrors[i]) { // not required
			continue
		}

		if m.ResourceTypeErrors[i] != nil {
			if err := m.ResourceTypeErrors[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("resource_type_errors" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *ScanWithSummaryAllOf1) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ScanWithSummaryAllOf1) UnmarshalBinary(b []byte) error {
	var res ScanWithSummaryAllOf1
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
