// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// UpdateCustomRuleInput Input request for updating a custom rule
// swagger:model UpdateCustomRuleInput
type UpdateCustomRuleInput struct {

	// Description of the custom rule
	Description string `json:"description,omitempty"`

	// Human readable name of the custom rule
	Name string `json:"name,omitempty"`

	// Rego code used by the rule
	RuleText string `json:"rule_text,omitempty"`

	// Status of the custom rule
	// Enum: [ENABLED DISABLED]
	Status string `json:"status,omitempty"`
}

// Validate validates this update custom rule input
func (m *UpdateCustomRuleInput) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateStatus(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

var updateCustomRuleInputTypeStatusPropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["ENABLED","DISABLED"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		updateCustomRuleInputTypeStatusPropEnum = append(updateCustomRuleInputTypeStatusPropEnum, v)
	}
}

const (

	// UpdateCustomRuleInputStatusENABLED captures enum value "ENABLED"
	UpdateCustomRuleInputStatusENABLED string = "ENABLED"

	// UpdateCustomRuleInputStatusDISABLED captures enum value "DISABLED"
	UpdateCustomRuleInputStatusDISABLED string = "DISABLED"
)

// prop value enum
func (m *UpdateCustomRuleInput) validateStatusEnum(path, location string, value string) error {
	if err := validate.Enum(path, location, value, updateCustomRuleInputTypeStatusPropEnum); err != nil {
		return err
	}
	return nil
}

func (m *UpdateCustomRuleInput) validateStatus(formats strfmt.Registry) error {

	if swag.IsZero(m.Status) { // not required
		return nil
	}

	// value enum
	if err := m.validateStatusEnum("status", "body", m.Status); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *UpdateCustomRuleInput) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *UpdateCustomRuleInput) UnmarshalBinary(b []byte) error {
	var res UpdateCustomRuleInput
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
