// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// ValidateCustomRuleInput Input request for validating a custom rule
// swagger:model ValidateCustomRuleInput
type ValidateCustomRuleInput struct {

	// Resource type to which the rule applies
	ResourceType string `json:"resource_type,omitempty"`

	// Rego code to be validated
	RuleText string `json:"rule_text,omitempty"`
}

// Validate validates this validate custom rule input
func (m *ValidateCustomRuleInput) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ValidateCustomRuleInput) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ValidateCustomRuleInput) UnmarshalBinary(b []byte) error {
	var res ValidateCustomRuleInput
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
